//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 11:38:08 AM IST 
//


package info.inetsolv;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the info.inetsolv package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Students_QNAME = new QName("http://www.info/inetsolv/students", "students");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: info.inetsolv
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Studentstype }
     * 
     */
    public Studentstype createStudentstype() {
        return new Studentstype();
    }

    /**
     * Create an instance of {@link StudentType }
     * 
     */
    public StudentType createStudentType() {
        return new StudentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Studentstype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.info/inetsolv/students", name = "students")
    public JAXBElement<Studentstype> createStudents(Studentstype value) {
        return new JAXBElement<Studentstype>(_Students_QNAME, Studentstype.class, null, value);
    }

}
