//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 11:38:08 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.info/inetsolv/students", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.inetsolv;
